#!/bin/bash

architecture=$(uname -m)

case $architecture in
    "x86_64")
        ARQ="1p"
        ;;
    "aarch64")
        ARQ="3p"
        ;;
    *)
        echo "Arquitectura desconocida: $architecture"
        ;;
esac

wget "$(curl -s https://nodejs.org/en/download | grep -oP '"([^"]*\.tar\.xz)"[^>]*' | sed 's/"//g' | sed -n $ARQ)"

tar -xf node*.tar.xz

rm -rf node*.tar.xz

mv node-* node

cd node

mkdir -p /usr/local/node

cp -R * /usr/local/node

path="export PATH=/usr/local/node/bin:$PATH"
echo $path >> ~/.bashrc
source ~/.bashrc

echo "versiones:"
echo "node"
node -v
echo "npm"
npm -v

cd ..
rm -rf node/
